#pragma once
#include <windows.h>
#include <stdio.h>
#include <tchar.h>
#include <strsafe.h>
#include <stdint.h>


typedef struct t_ERROR_STRING_PAIR
{
  int          err_code;
  _TCHAR* err_string;
} ERROR_STRING_PAIR;


class MpcApiError
{
public:
  MpcApiError(void);
  static BOOL Init();
  static _TCHAR* GetErrorDescription(int errorCode);
  virtual ~MpcApiError(void);
  enum 
  {
    ERR_OK,
    ERR_INITIALIZATION_FAILED = 0x3001,
    ERR_DEINITIALIZATION_FAILED, //0x3002
    ERR_GET_DEVICE_NUMBER_FAILED, //0x3003
    ERR_GET_DEVICE_HANDLE_FAILED, //0x3004
    ERR_COMMUNICATION_INITIALIZE_FAILED, //0x3005
    ERR_COMMUNICATION_FAILED, //0x3006
    ERR_FILE_NAME_TOO_LONG, //0x3007
    ERR_OPEN_LOCAL_FILE_FAILED, //0x3008
    ERR_INVALID_FILE_INFORMATION, //0x3009
    ERR_SCRIPT_CONVERT_FAILED, //0x300a
    ERR_LOAD_PYTHON_MODULE_FAILED, //0x300b
    ERR_PYTHON_VERSION_NOT_MATCH, //0x300c
    ERR_INVALID_DEVICE_HANDLE, //0x300d
    ERR_DEVICE_NOT_CONNECTED, //0x300e
    ERR_INSUFICIENT_SCRIPT_DATA, //0x300f
    ERR_FILE_NOT_FOUND, //0x3010
    ERR_NOT_INITIALIZED, //0x3011
    ERR_COMMAND_VALIDATION_FAILED, //0x3012
    ERR_SET_ABORT_UPDATE_FIRMWARE_FAILED, //0x3013
    ERR_UPDATE_FIRMWARE_ABORTED, //0x3014
    ERR_INSUFFICIENT_SCRIPT_OUTPUT_BUFFER, //0x3015
    ERR_ARG_LIST_TOO_LONG, //0x3016
    ERR_SCRIPT_EXE_FAILED, //0x3017
    ERR_HID_NULL_REPORT_DESC, // 0x3018
    ERR_HID_LENGTH_FAILED, //0x3019
    ERR_HID_TABLE_FAILED, //0x301a
    ERR_HID_VALUE_RANGE_FAILED, //0x301b
    ERR_HID_ENUM_FAILED, //0x301c
    ERR_HID_SWITCH_MODE_FAILED, //0x301d
    ERR_HID_REPORT_UNAVAILABLE, //0x301e
    ERR_FP_COMMAND_FAILED, //0x301f
    ERR_FP_INVALID_SENSOR_TYPE, //0x3020
    ERR_FP_INVALID_PARAMS, //0x3021
    ERR_PARAM_VLIDATION_FAILED = 0x3ffe,
    ERR_NOT_IMPLEMENTED = 0x3fff,
    ERR_MAX
  };
    
private :
  static ERROR_STRING_PAIR* m_pErrorStringPair;
};
