/********************************************************************************
** Form generated from reading UI file 'Syn_BinCodesDlg.ui'
**
** Created by: Qt User Interface Compiler version 5.5.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SYN_BINCODESDLG_H
#define UI_SYN_BINCODESDLG_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpacerItem>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Syn_BinCodesDlg
{
public:
    QGridLayout *gridLayout;
    QGroupBox *BinCodesGroupBox;
    QGridLayout *gridLayout_2;
    QTableWidget *BinCodesTableWidget;
    QHBoxLayout *horizontalLayout_2;
    QSpacerItem *horizontalSpacer;
    QPushButton *ClosePushButton;

    void setupUi(QWidget *Syn_BinCodesDlg)
    {
        if (Syn_BinCodesDlg->objectName().isEmpty())
            Syn_BinCodesDlg->setObjectName(QStringLiteral("Syn_BinCodesDlg"));
        Syn_BinCodesDlg->resize(414, 446);
        gridLayout = new QGridLayout(Syn_BinCodesDlg);
        gridLayout->setSpacing(6);
        gridLayout->setContentsMargins(11, 11, 11, 11);
        gridLayout->setObjectName(QStringLiteral("gridLayout"));
        BinCodesGroupBox = new QGroupBox(Syn_BinCodesDlg);
        BinCodesGroupBox->setObjectName(QStringLiteral("BinCodesGroupBox"));
        gridLayout_2 = new QGridLayout(BinCodesGroupBox);
        gridLayout_2->setSpacing(6);
        gridLayout_2->setContentsMargins(11, 11, 11, 11);
        gridLayout_2->setObjectName(QStringLiteral("gridLayout_2"));
        BinCodesTableWidget = new QTableWidget(BinCodesGroupBox);
        if (BinCodesTableWidget->columnCount() < 3)
            BinCodesTableWidget->setColumnCount(3);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        BinCodesTableWidget->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        BinCodesTableWidget->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        BinCodesTableWidget->setHorizontalHeaderItem(2, __qtablewidgetitem2);
        if (BinCodesTableWidget->rowCount() < 58)
            BinCodesTableWidget->setRowCount(58);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(0, __qtablewidgetitem3);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(1, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(2, __qtablewidgetitem5);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(3, __qtablewidgetitem6);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(4, __qtablewidgetitem7);
        QTableWidgetItem *__qtablewidgetitem8 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(5, __qtablewidgetitem8);
        QTableWidgetItem *__qtablewidgetitem9 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(6, __qtablewidgetitem9);
        QTableWidgetItem *__qtablewidgetitem10 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(7, __qtablewidgetitem10);
        QTableWidgetItem *__qtablewidgetitem11 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(8, __qtablewidgetitem11);
        QTableWidgetItem *__qtablewidgetitem12 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(9, __qtablewidgetitem12);
        QTableWidgetItem *__qtablewidgetitem13 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(10, __qtablewidgetitem13);
        QTableWidgetItem *__qtablewidgetitem14 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(11, __qtablewidgetitem14);
        QTableWidgetItem *__qtablewidgetitem15 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(12, __qtablewidgetitem15);
        QTableWidgetItem *__qtablewidgetitem16 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(13, __qtablewidgetitem16);
        QTableWidgetItem *__qtablewidgetitem17 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(14, __qtablewidgetitem17);
        QTableWidgetItem *__qtablewidgetitem18 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(15, __qtablewidgetitem18);
        QTableWidgetItem *__qtablewidgetitem19 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(16, __qtablewidgetitem19);
        QTableWidgetItem *__qtablewidgetitem20 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(17, __qtablewidgetitem20);
        QTableWidgetItem *__qtablewidgetitem21 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(18, __qtablewidgetitem21);
        QTableWidgetItem *__qtablewidgetitem22 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(19, __qtablewidgetitem22);
        QTableWidgetItem *__qtablewidgetitem23 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(20, __qtablewidgetitem23);
        QTableWidgetItem *__qtablewidgetitem24 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(21, __qtablewidgetitem24);
        QTableWidgetItem *__qtablewidgetitem25 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(22, __qtablewidgetitem25);
        QTableWidgetItem *__qtablewidgetitem26 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(23, __qtablewidgetitem26);
        QTableWidgetItem *__qtablewidgetitem27 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(24, __qtablewidgetitem27);
        QTableWidgetItem *__qtablewidgetitem28 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(25, __qtablewidgetitem28);
        QTableWidgetItem *__qtablewidgetitem29 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(26, __qtablewidgetitem29);
        QTableWidgetItem *__qtablewidgetitem30 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(27, __qtablewidgetitem30);
        QTableWidgetItem *__qtablewidgetitem31 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(28, __qtablewidgetitem31);
        QTableWidgetItem *__qtablewidgetitem32 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(29, __qtablewidgetitem32);
        QTableWidgetItem *__qtablewidgetitem33 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(30, __qtablewidgetitem33);
        QTableWidgetItem *__qtablewidgetitem34 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(31, __qtablewidgetitem34);
        QTableWidgetItem *__qtablewidgetitem35 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(32, __qtablewidgetitem35);
        QTableWidgetItem *__qtablewidgetitem36 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(33, __qtablewidgetitem36);
        QTableWidgetItem *__qtablewidgetitem37 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(34, __qtablewidgetitem37);
        QTableWidgetItem *__qtablewidgetitem38 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(35, __qtablewidgetitem38);
        QTableWidgetItem *__qtablewidgetitem39 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(36, __qtablewidgetitem39);
        QTableWidgetItem *__qtablewidgetitem40 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(37, __qtablewidgetitem40);
        QTableWidgetItem *__qtablewidgetitem41 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(38, __qtablewidgetitem41);
        QTableWidgetItem *__qtablewidgetitem42 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(39, __qtablewidgetitem42);
        QTableWidgetItem *__qtablewidgetitem43 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(40, __qtablewidgetitem43);
        QTableWidgetItem *__qtablewidgetitem44 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(41, __qtablewidgetitem44);
        QTableWidgetItem *__qtablewidgetitem45 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(42, __qtablewidgetitem45);
        QTableWidgetItem *__qtablewidgetitem46 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(43, __qtablewidgetitem46);
        QTableWidgetItem *__qtablewidgetitem47 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(44, __qtablewidgetitem47);
        QTableWidgetItem *__qtablewidgetitem48 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(45, __qtablewidgetitem48);
        QTableWidgetItem *__qtablewidgetitem49 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(46, __qtablewidgetitem49);
        QTableWidgetItem *__qtablewidgetitem50 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(47, __qtablewidgetitem50);
        QTableWidgetItem *__qtablewidgetitem51 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(48, __qtablewidgetitem51);
        QTableWidgetItem *__qtablewidgetitem52 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(49, __qtablewidgetitem52);
        QTableWidgetItem *__qtablewidgetitem53 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(50, __qtablewidgetitem53);
        QTableWidgetItem *__qtablewidgetitem54 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(51, __qtablewidgetitem54);
        QTableWidgetItem *__qtablewidgetitem55 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(52, __qtablewidgetitem55);
        QTableWidgetItem *__qtablewidgetitem56 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(53, __qtablewidgetitem56);
        QTableWidgetItem *__qtablewidgetitem57 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(54, __qtablewidgetitem57);
        QTableWidgetItem *__qtablewidgetitem58 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(55, __qtablewidgetitem58);
        QTableWidgetItem *__qtablewidgetitem59 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(56, __qtablewidgetitem59);
        QTableWidgetItem *__qtablewidgetitem60 = new QTableWidgetItem();
        BinCodesTableWidget->setVerticalHeaderItem(57, __qtablewidgetitem60);
        QTableWidgetItem *__qtablewidgetitem61 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(0, 0, __qtablewidgetitem61);
        QTableWidgetItem *__qtablewidgetitem62 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(0, 1, __qtablewidgetitem62);
        QTableWidgetItem *__qtablewidgetitem63 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(0, 2, __qtablewidgetitem63);
        QTableWidgetItem *__qtablewidgetitem64 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(1, 0, __qtablewidgetitem64);
        QTableWidgetItem *__qtablewidgetitem65 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(1, 1, __qtablewidgetitem65);
        QTableWidgetItem *__qtablewidgetitem66 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(1, 2, __qtablewidgetitem66);
        QTableWidgetItem *__qtablewidgetitem67 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(2, 0, __qtablewidgetitem67);
        QTableWidgetItem *__qtablewidgetitem68 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(2, 2, __qtablewidgetitem68);
        QTableWidgetItem *__qtablewidgetitem69 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(3, 0, __qtablewidgetitem69);
        QTableWidgetItem *__qtablewidgetitem70 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(3, 1, __qtablewidgetitem70);
        QTableWidgetItem *__qtablewidgetitem71 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(3, 2, __qtablewidgetitem71);
        QTableWidgetItem *__qtablewidgetitem72 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(4, 0, __qtablewidgetitem72);
        QTableWidgetItem *__qtablewidgetitem73 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(4, 1, __qtablewidgetitem73);
        QTableWidgetItem *__qtablewidgetitem74 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(4, 2, __qtablewidgetitem74);
        QTableWidgetItem *__qtablewidgetitem75 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(5, 0, __qtablewidgetitem75);
        QTableWidgetItem *__qtablewidgetitem76 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(5, 1, __qtablewidgetitem76);
        QTableWidgetItem *__qtablewidgetitem77 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(5, 2, __qtablewidgetitem77);
        QTableWidgetItem *__qtablewidgetitem78 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(6, 0, __qtablewidgetitem78);
        QTableWidgetItem *__qtablewidgetitem79 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(6, 1, __qtablewidgetitem79);
        QTableWidgetItem *__qtablewidgetitem80 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(6, 2, __qtablewidgetitem80);
        QTableWidgetItem *__qtablewidgetitem81 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(7, 0, __qtablewidgetitem81);
        QTableWidgetItem *__qtablewidgetitem82 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(7, 1, __qtablewidgetitem82);
        QTableWidgetItem *__qtablewidgetitem83 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(7, 2, __qtablewidgetitem83);
        QTableWidgetItem *__qtablewidgetitem84 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(8, 0, __qtablewidgetitem84);
        QTableWidgetItem *__qtablewidgetitem85 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(8, 1, __qtablewidgetitem85);
        QTableWidgetItem *__qtablewidgetitem86 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(8, 2, __qtablewidgetitem86);
        QTableWidgetItem *__qtablewidgetitem87 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(9, 0, __qtablewidgetitem87);
        QTableWidgetItem *__qtablewidgetitem88 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(9, 1, __qtablewidgetitem88);
        QTableWidgetItem *__qtablewidgetitem89 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(9, 2, __qtablewidgetitem89);
        QTableWidgetItem *__qtablewidgetitem90 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(10, 0, __qtablewidgetitem90);
        QTableWidgetItem *__qtablewidgetitem91 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(10, 1, __qtablewidgetitem91);
        QTableWidgetItem *__qtablewidgetitem92 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(10, 2, __qtablewidgetitem92);
        QTableWidgetItem *__qtablewidgetitem93 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(11, 0, __qtablewidgetitem93);
        QTableWidgetItem *__qtablewidgetitem94 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(11, 1, __qtablewidgetitem94);
        QTableWidgetItem *__qtablewidgetitem95 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(11, 2, __qtablewidgetitem95);
        QTableWidgetItem *__qtablewidgetitem96 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(12, 0, __qtablewidgetitem96);
        QTableWidgetItem *__qtablewidgetitem97 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(12, 1, __qtablewidgetitem97);
        QTableWidgetItem *__qtablewidgetitem98 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(12, 2, __qtablewidgetitem98);
        QTableWidgetItem *__qtablewidgetitem99 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(13, 0, __qtablewidgetitem99);
        QTableWidgetItem *__qtablewidgetitem100 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(13, 1, __qtablewidgetitem100);
        QTableWidgetItem *__qtablewidgetitem101 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(13, 2, __qtablewidgetitem101);
        QTableWidgetItem *__qtablewidgetitem102 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(14, 0, __qtablewidgetitem102);
        QTableWidgetItem *__qtablewidgetitem103 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(14, 1, __qtablewidgetitem103);
        QTableWidgetItem *__qtablewidgetitem104 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(14, 2, __qtablewidgetitem104);
        QTableWidgetItem *__qtablewidgetitem105 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(15, 0, __qtablewidgetitem105);
        QTableWidgetItem *__qtablewidgetitem106 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(15, 1, __qtablewidgetitem106);
        QTableWidgetItem *__qtablewidgetitem107 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(15, 2, __qtablewidgetitem107);
        QTableWidgetItem *__qtablewidgetitem108 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(16, 0, __qtablewidgetitem108);
        QTableWidgetItem *__qtablewidgetitem109 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(16, 1, __qtablewidgetitem109);
        QTableWidgetItem *__qtablewidgetitem110 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(16, 2, __qtablewidgetitem110);
        QTableWidgetItem *__qtablewidgetitem111 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(17, 0, __qtablewidgetitem111);
        QTableWidgetItem *__qtablewidgetitem112 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(17, 1, __qtablewidgetitem112);
        QTableWidgetItem *__qtablewidgetitem113 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(17, 2, __qtablewidgetitem113);
        QTableWidgetItem *__qtablewidgetitem114 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(18, 0, __qtablewidgetitem114);
        QTableWidgetItem *__qtablewidgetitem115 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(18, 1, __qtablewidgetitem115);
        QTableWidgetItem *__qtablewidgetitem116 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(18, 2, __qtablewidgetitem116);
        QTableWidgetItem *__qtablewidgetitem117 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(19, 0, __qtablewidgetitem117);
        QTableWidgetItem *__qtablewidgetitem118 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(19, 1, __qtablewidgetitem118);
        QTableWidgetItem *__qtablewidgetitem119 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(19, 2, __qtablewidgetitem119);
        QTableWidgetItem *__qtablewidgetitem120 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(20, 0, __qtablewidgetitem120);
        QTableWidgetItem *__qtablewidgetitem121 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(20, 1, __qtablewidgetitem121);
        QTableWidgetItem *__qtablewidgetitem122 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(20, 2, __qtablewidgetitem122);
        QTableWidgetItem *__qtablewidgetitem123 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(21, 0, __qtablewidgetitem123);
        QTableWidgetItem *__qtablewidgetitem124 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(21, 1, __qtablewidgetitem124);
        QTableWidgetItem *__qtablewidgetitem125 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(21, 2, __qtablewidgetitem125);
        QTableWidgetItem *__qtablewidgetitem126 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(22, 0, __qtablewidgetitem126);
        QTableWidgetItem *__qtablewidgetitem127 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(22, 1, __qtablewidgetitem127);
        QTableWidgetItem *__qtablewidgetitem128 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(22, 2, __qtablewidgetitem128);
        QTableWidgetItem *__qtablewidgetitem129 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(23, 0, __qtablewidgetitem129);
        QTableWidgetItem *__qtablewidgetitem130 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(23, 1, __qtablewidgetitem130);
        QTableWidgetItem *__qtablewidgetitem131 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(23, 2, __qtablewidgetitem131);
        QTableWidgetItem *__qtablewidgetitem132 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(24, 0, __qtablewidgetitem132);
        QTableWidgetItem *__qtablewidgetitem133 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(24, 1, __qtablewidgetitem133);
        QTableWidgetItem *__qtablewidgetitem134 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(24, 2, __qtablewidgetitem134);
        QTableWidgetItem *__qtablewidgetitem135 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(25, 0, __qtablewidgetitem135);
        QTableWidgetItem *__qtablewidgetitem136 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(25, 1, __qtablewidgetitem136);
        QTableWidgetItem *__qtablewidgetitem137 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(25, 2, __qtablewidgetitem137);
        QTableWidgetItem *__qtablewidgetitem138 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(26, 0, __qtablewidgetitem138);
        QTableWidgetItem *__qtablewidgetitem139 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(26, 1, __qtablewidgetitem139);
        QTableWidgetItem *__qtablewidgetitem140 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(26, 2, __qtablewidgetitem140);
        QTableWidgetItem *__qtablewidgetitem141 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(27, 0, __qtablewidgetitem141);
        QTableWidgetItem *__qtablewidgetitem142 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(27, 1, __qtablewidgetitem142);
        QTableWidgetItem *__qtablewidgetitem143 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(27, 2, __qtablewidgetitem143);
        QTableWidgetItem *__qtablewidgetitem144 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(28, 0, __qtablewidgetitem144);
        QTableWidgetItem *__qtablewidgetitem145 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(28, 1, __qtablewidgetitem145);
        QTableWidgetItem *__qtablewidgetitem146 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(28, 2, __qtablewidgetitem146);
        QTableWidgetItem *__qtablewidgetitem147 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(29, 0, __qtablewidgetitem147);
        QTableWidgetItem *__qtablewidgetitem148 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(29, 1, __qtablewidgetitem148);
        QTableWidgetItem *__qtablewidgetitem149 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(29, 2, __qtablewidgetitem149);
        QTableWidgetItem *__qtablewidgetitem150 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(30, 0, __qtablewidgetitem150);
        QTableWidgetItem *__qtablewidgetitem151 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(30, 1, __qtablewidgetitem151);
        QTableWidgetItem *__qtablewidgetitem152 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(30, 2, __qtablewidgetitem152);
        QTableWidgetItem *__qtablewidgetitem153 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(31, 0, __qtablewidgetitem153);
        QTableWidgetItem *__qtablewidgetitem154 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(31, 1, __qtablewidgetitem154);
        QTableWidgetItem *__qtablewidgetitem155 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(31, 2, __qtablewidgetitem155);
        QTableWidgetItem *__qtablewidgetitem156 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(32, 0, __qtablewidgetitem156);
        QTableWidgetItem *__qtablewidgetitem157 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(32, 1, __qtablewidgetitem157);
        QTableWidgetItem *__qtablewidgetitem158 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(32, 2, __qtablewidgetitem158);
        QTableWidgetItem *__qtablewidgetitem159 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(33, 0, __qtablewidgetitem159);
        QTableWidgetItem *__qtablewidgetitem160 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(33, 1, __qtablewidgetitem160);
        QTableWidgetItem *__qtablewidgetitem161 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(33, 2, __qtablewidgetitem161);
        QTableWidgetItem *__qtablewidgetitem162 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(34, 0, __qtablewidgetitem162);
        QTableWidgetItem *__qtablewidgetitem163 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(34, 1, __qtablewidgetitem163);
        QTableWidgetItem *__qtablewidgetitem164 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(34, 2, __qtablewidgetitem164);
        QTableWidgetItem *__qtablewidgetitem165 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(35, 0, __qtablewidgetitem165);
        QTableWidgetItem *__qtablewidgetitem166 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(35, 1, __qtablewidgetitem166);
        QTableWidgetItem *__qtablewidgetitem167 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(35, 2, __qtablewidgetitem167);
        QTableWidgetItem *__qtablewidgetitem168 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(36, 0, __qtablewidgetitem168);
        QTableWidgetItem *__qtablewidgetitem169 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(36, 1, __qtablewidgetitem169);
        QTableWidgetItem *__qtablewidgetitem170 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(36, 2, __qtablewidgetitem170);
        QTableWidgetItem *__qtablewidgetitem171 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(37, 0, __qtablewidgetitem171);
        QTableWidgetItem *__qtablewidgetitem172 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(37, 1, __qtablewidgetitem172);
        QTableWidgetItem *__qtablewidgetitem173 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(37, 2, __qtablewidgetitem173);
        QTableWidgetItem *__qtablewidgetitem174 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(38, 0, __qtablewidgetitem174);
        QTableWidgetItem *__qtablewidgetitem175 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(38, 1, __qtablewidgetitem175);
        QTableWidgetItem *__qtablewidgetitem176 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(38, 2, __qtablewidgetitem176);
        QTableWidgetItem *__qtablewidgetitem177 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(39, 0, __qtablewidgetitem177);
        QTableWidgetItem *__qtablewidgetitem178 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(39, 1, __qtablewidgetitem178);
        QTableWidgetItem *__qtablewidgetitem179 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(39, 2, __qtablewidgetitem179);
        QTableWidgetItem *__qtablewidgetitem180 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(40, 0, __qtablewidgetitem180);
        QTableWidgetItem *__qtablewidgetitem181 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(40, 1, __qtablewidgetitem181);
        QTableWidgetItem *__qtablewidgetitem182 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(40, 2, __qtablewidgetitem182);
        QTableWidgetItem *__qtablewidgetitem183 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(41, 0, __qtablewidgetitem183);
        QTableWidgetItem *__qtablewidgetitem184 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(41, 1, __qtablewidgetitem184);
        QTableWidgetItem *__qtablewidgetitem185 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(41, 2, __qtablewidgetitem185);
        QTableWidgetItem *__qtablewidgetitem186 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(42, 0, __qtablewidgetitem186);
        QTableWidgetItem *__qtablewidgetitem187 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(42, 1, __qtablewidgetitem187);
        QTableWidgetItem *__qtablewidgetitem188 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(42, 2, __qtablewidgetitem188);
        QTableWidgetItem *__qtablewidgetitem189 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(43, 0, __qtablewidgetitem189);
        QTableWidgetItem *__qtablewidgetitem190 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(43, 1, __qtablewidgetitem190);
        QTableWidgetItem *__qtablewidgetitem191 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(43, 2, __qtablewidgetitem191);
        QTableWidgetItem *__qtablewidgetitem192 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(44, 0, __qtablewidgetitem192);
        QTableWidgetItem *__qtablewidgetitem193 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(44, 1, __qtablewidgetitem193);
        QTableWidgetItem *__qtablewidgetitem194 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(44, 2, __qtablewidgetitem194);
        QTableWidgetItem *__qtablewidgetitem195 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(45, 0, __qtablewidgetitem195);
        QTableWidgetItem *__qtablewidgetitem196 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(45, 1, __qtablewidgetitem196);
        QTableWidgetItem *__qtablewidgetitem197 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(45, 2, __qtablewidgetitem197);
        QTableWidgetItem *__qtablewidgetitem198 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(46, 0, __qtablewidgetitem198);
        QTableWidgetItem *__qtablewidgetitem199 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(46, 1, __qtablewidgetitem199);
        QTableWidgetItem *__qtablewidgetitem200 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(46, 2, __qtablewidgetitem200);
        QTableWidgetItem *__qtablewidgetitem201 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(47, 0, __qtablewidgetitem201);
        QTableWidgetItem *__qtablewidgetitem202 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(47, 1, __qtablewidgetitem202);
        QTableWidgetItem *__qtablewidgetitem203 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(47, 2, __qtablewidgetitem203);
        QTableWidgetItem *__qtablewidgetitem204 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(48, 0, __qtablewidgetitem204);
        QTableWidgetItem *__qtablewidgetitem205 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(48, 1, __qtablewidgetitem205);
        QTableWidgetItem *__qtablewidgetitem206 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(48, 2, __qtablewidgetitem206);
        QTableWidgetItem *__qtablewidgetitem207 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(49, 0, __qtablewidgetitem207);
        QTableWidgetItem *__qtablewidgetitem208 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(49, 1, __qtablewidgetitem208);
        QTableWidgetItem *__qtablewidgetitem209 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(49, 2, __qtablewidgetitem209);
        QTableWidgetItem *__qtablewidgetitem210 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(50, 0, __qtablewidgetitem210);
        QTableWidgetItem *__qtablewidgetitem211 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(50, 1, __qtablewidgetitem211);
        QTableWidgetItem *__qtablewidgetitem212 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(50, 2, __qtablewidgetitem212);
        QTableWidgetItem *__qtablewidgetitem213 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(51, 0, __qtablewidgetitem213);
        QTableWidgetItem *__qtablewidgetitem214 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(51, 1, __qtablewidgetitem214);
        QTableWidgetItem *__qtablewidgetitem215 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(51, 2, __qtablewidgetitem215);
        QTableWidgetItem *__qtablewidgetitem216 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(52, 0, __qtablewidgetitem216);
        QTableWidgetItem *__qtablewidgetitem217 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(52, 1, __qtablewidgetitem217);
        QTableWidgetItem *__qtablewidgetitem218 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(52, 2, __qtablewidgetitem218);
        QTableWidgetItem *__qtablewidgetitem219 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(53, 0, __qtablewidgetitem219);
        QTableWidgetItem *__qtablewidgetitem220 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(53, 1, __qtablewidgetitem220);
        QTableWidgetItem *__qtablewidgetitem221 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(53, 2, __qtablewidgetitem221);
        QTableWidgetItem *__qtablewidgetitem222 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(54, 0, __qtablewidgetitem222);
        QTableWidgetItem *__qtablewidgetitem223 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(54, 1, __qtablewidgetitem223);
        QTableWidgetItem *__qtablewidgetitem224 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(54, 2, __qtablewidgetitem224);
        QTableWidgetItem *__qtablewidgetitem225 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(55, 0, __qtablewidgetitem225);
        QTableWidgetItem *__qtablewidgetitem226 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(55, 1, __qtablewidgetitem226);
        QTableWidgetItem *__qtablewidgetitem227 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(55, 2, __qtablewidgetitem227);
        QTableWidgetItem *__qtablewidgetitem228 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(56, 0, __qtablewidgetitem228);
        QTableWidgetItem *__qtablewidgetitem229 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(56, 1, __qtablewidgetitem229);
        QTableWidgetItem *__qtablewidgetitem230 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(57, 0, __qtablewidgetitem230);
        QTableWidgetItem *__qtablewidgetitem231 = new QTableWidgetItem();
        BinCodesTableWidget->setItem(57, 1, __qtablewidgetitem231);
        BinCodesTableWidget->setObjectName(QStringLiteral("BinCodesTableWidget"));
        BinCodesTableWidget->setSelectionMode(QAbstractItemView::SingleSelection);
        BinCodesTableWidget->setSelectionBehavior(QAbstractItemView::SelectRows);

        gridLayout_2->addWidget(BinCodesTableWidget, 0, 0, 1, 1);


        gridLayout->addWidget(BinCodesGroupBox, 0, 0, 1, 1);

        horizontalLayout_2 = new QHBoxLayout();
        horizontalLayout_2->setSpacing(6);
        horizontalLayout_2->setObjectName(QStringLiteral("horizontalLayout_2"));
        horizontalSpacer = new QSpacerItem(37, 17, QSizePolicy::Expanding, QSizePolicy::Minimum);

        horizontalLayout_2->addItem(horizontalSpacer);

        ClosePushButton = new QPushButton(Syn_BinCodesDlg);
        ClosePushButton->setObjectName(QStringLiteral("ClosePushButton"));

        horizontalLayout_2->addWidget(ClosePushButton);


        gridLayout->addLayout(horizontalLayout_2, 1, 0, 1, 1);


        retranslateUi(Syn_BinCodesDlg);

        QMetaObject::connectSlotsByName(Syn_BinCodesDlg);
    } // setupUi

    void retranslateUi(QWidget *Syn_BinCodesDlg)
    {
        Syn_BinCodesDlg->setWindowTitle(QApplication::translate("Syn_BinCodesDlg", "BinCodes Display", 0));
        BinCodesGroupBox->setTitle(QApplication::translate("Syn_BinCodesDlg", "BinCodes", 0));
        QTableWidgetItem *___qtablewidgetitem = BinCodesTableWidget->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QApplication::translate("Syn_BinCodesDlg", "BinCodes", 0));
        QTableWidgetItem *___qtablewidgetitem1 = BinCodesTableWidget->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QApplication::translate("Syn_BinCodesDlg", "Test Name", 0));
        QTableWidgetItem *___qtablewidgetitem2 = BinCodesTableWidget->horizontalHeaderItem(2);
        ___qtablewidgetitem2->setText(QApplication::translate("Syn_BinCodesDlg", "Failure modes detected", 0));
        QTableWidgetItem *___qtablewidgetitem3 = BinCodesTableWidget->verticalHeaderItem(0);
        ___qtablewidgetitem3->setText(QApplication::translate("Syn_BinCodesDlg", "1", 0));
        QTableWidgetItem *___qtablewidgetitem4 = BinCodesTableWidget->verticalHeaderItem(1);
        ___qtablewidgetitem4->setText(QApplication::translate("Syn_BinCodesDlg", "2", 0));
        QTableWidgetItem *___qtablewidgetitem5 = BinCodesTableWidget->verticalHeaderItem(2);
        ___qtablewidgetitem5->setText(QApplication::translate("Syn_BinCodesDlg", "3", 0));
        QTableWidgetItem *___qtablewidgetitem6 = BinCodesTableWidget->verticalHeaderItem(3);
        ___qtablewidgetitem6->setText(QApplication::translate("Syn_BinCodesDlg", "4", 0));
        QTableWidgetItem *___qtablewidgetitem7 = BinCodesTableWidget->verticalHeaderItem(4);
        ___qtablewidgetitem7->setText(QApplication::translate("Syn_BinCodesDlg", "5", 0));
        QTableWidgetItem *___qtablewidgetitem8 = BinCodesTableWidget->verticalHeaderItem(5);
        ___qtablewidgetitem8->setText(QApplication::translate("Syn_BinCodesDlg", "6", 0));
        QTableWidgetItem *___qtablewidgetitem9 = BinCodesTableWidget->verticalHeaderItem(6);
        ___qtablewidgetitem9->setText(QApplication::translate("Syn_BinCodesDlg", "7", 0));
        QTableWidgetItem *___qtablewidgetitem10 = BinCodesTableWidget->verticalHeaderItem(7);
        ___qtablewidgetitem10->setText(QApplication::translate("Syn_BinCodesDlg", "8", 0));
        QTableWidgetItem *___qtablewidgetitem11 = BinCodesTableWidget->verticalHeaderItem(8);
        ___qtablewidgetitem11->setText(QApplication::translate("Syn_BinCodesDlg", "9", 0));
        QTableWidgetItem *___qtablewidgetitem12 = BinCodesTableWidget->verticalHeaderItem(9);
        ___qtablewidgetitem12->setText(QApplication::translate("Syn_BinCodesDlg", "10", 0));
        QTableWidgetItem *___qtablewidgetitem13 = BinCodesTableWidget->verticalHeaderItem(10);
        ___qtablewidgetitem13->setText(QApplication::translate("Syn_BinCodesDlg", "11", 0));
        QTableWidgetItem *___qtablewidgetitem14 = BinCodesTableWidget->verticalHeaderItem(11);
        ___qtablewidgetitem14->setText(QApplication::translate("Syn_BinCodesDlg", "12", 0));
        QTableWidgetItem *___qtablewidgetitem15 = BinCodesTableWidget->verticalHeaderItem(12);
        ___qtablewidgetitem15->setText(QApplication::translate("Syn_BinCodesDlg", "13", 0));
        QTableWidgetItem *___qtablewidgetitem16 = BinCodesTableWidget->verticalHeaderItem(13);
        ___qtablewidgetitem16->setText(QApplication::translate("Syn_BinCodesDlg", "14", 0));
        QTableWidgetItem *___qtablewidgetitem17 = BinCodesTableWidget->verticalHeaderItem(14);
        ___qtablewidgetitem17->setText(QApplication::translate("Syn_BinCodesDlg", "15", 0));
        QTableWidgetItem *___qtablewidgetitem18 = BinCodesTableWidget->verticalHeaderItem(15);
        ___qtablewidgetitem18->setText(QApplication::translate("Syn_BinCodesDlg", "16", 0));
        QTableWidgetItem *___qtablewidgetitem19 = BinCodesTableWidget->verticalHeaderItem(16);
        ___qtablewidgetitem19->setText(QApplication::translate("Syn_BinCodesDlg", "17", 0));
        QTableWidgetItem *___qtablewidgetitem20 = BinCodesTableWidget->verticalHeaderItem(17);
        ___qtablewidgetitem20->setText(QApplication::translate("Syn_BinCodesDlg", "18", 0));
        QTableWidgetItem *___qtablewidgetitem21 = BinCodesTableWidget->verticalHeaderItem(18);
        ___qtablewidgetitem21->setText(QApplication::translate("Syn_BinCodesDlg", "19", 0));
        QTableWidgetItem *___qtablewidgetitem22 = BinCodesTableWidget->verticalHeaderItem(19);
        ___qtablewidgetitem22->setText(QApplication::translate("Syn_BinCodesDlg", "20", 0));
        QTableWidgetItem *___qtablewidgetitem23 = BinCodesTableWidget->verticalHeaderItem(20);
        ___qtablewidgetitem23->setText(QApplication::translate("Syn_BinCodesDlg", "21", 0));
        QTableWidgetItem *___qtablewidgetitem24 = BinCodesTableWidget->verticalHeaderItem(21);
        ___qtablewidgetitem24->setText(QApplication::translate("Syn_BinCodesDlg", "22", 0));
        QTableWidgetItem *___qtablewidgetitem25 = BinCodesTableWidget->verticalHeaderItem(22);
        ___qtablewidgetitem25->setText(QApplication::translate("Syn_BinCodesDlg", "23", 0));
        QTableWidgetItem *___qtablewidgetitem26 = BinCodesTableWidget->verticalHeaderItem(23);
        ___qtablewidgetitem26->setText(QApplication::translate("Syn_BinCodesDlg", "24", 0));
        QTableWidgetItem *___qtablewidgetitem27 = BinCodesTableWidget->verticalHeaderItem(24);
        ___qtablewidgetitem27->setText(QApplication::translate("Syn_BinCodesDlg", "25", 0));
        QTableWidgetItem *___qtablewidgetitem28 = BinCodesTableWidget->verticalHeaderItem(25);
        ___qtablewidgetitem28->setText(QApplication::translate("Syn_BinCodesDlg", "26", 0));
        QTableWidgetItem *___qtablewidgetitem29 = BinCodesTableWidget->verticalHeaderItem(26);
        ___qtablewidgetitem29->setText(QApplication::translate("Syn_BinCodesDlg", "27", 0));
        QTableWidgetItem *___qtablewidgetitem30 = BinCodesTableWidget->verticalHeaderItem(27);
        ___qtablewidgetitem30->setText(QApplication::translate("Syn_BinCodesDlg", "28", 0));
        QTableWidgetItem *___qtablewidgetitem31 = BinCodesTableWidget->verticalHeaderItem(28);
        ___qtablewidgetitem31->setText(QApplication::translate("Syn_BinCodesDlg", "29", 0));
        QTableWidgetItem *___qtablewidgetitem32 = BinCodesTableWidget->verticalHeaderItem(29);
        ___qtablewidgetitem32->setText(QApplication::translate("Syn_BinCodesDlg", "30", 0));
        QTableWidgetItem *___qtablewidgetitem33 = BinCodesTableWidget->verticalHeaderItem(30);
        ___qtablewidgetitem33->setText(QApplication::translate("Syn_BinCodesDlg", "31", 0));
        QTableWidgetItem *___qtablewidgetitem34 = BinCodesTableWidget->verticalHeaderItem(31);
        ___qtablewidgetitem34->setText(QApplication::translate("Syn_BinCodesDlg", "32", 0));
        QTableWidgetItem *___qtablewidgetitem35 = BinCodesTableWidget->verticalHeaderItem(32);
        ___qtablewidgetitem35->setText(QApplication::translate("Syn_BinCodesDlg", "33", 0));
        QTableWidgetItem *___qtablewidgetitem36 = BinCodesTableWidget->verticalHeaderItem(33);
        ___qtablewidgetitem36->setText(QApplication::translate("Syn_BinCodesDlg", "34", 0));
        QTableWidgetItem *___qtablewidgetitem37 = BinCodesTableWidget->verticalHeaderItem(34);
        ___qtablewidgetitem37->setText(QApplication::translate("Syn_BinCodesDlg", "35", 0));
        QTableWidgetItem *___qtablewidgetitem38 = BinCodesTableWidget->verticalHeaderItem(35);
        ___qtablewidgetitem38->setText(QApplication::translate("Syn_BinCodesDlg", "36", 0));
        QTableWidgetItem *___qtablewidgetitem39 = BinCodesTableWidget->verticalHeaderItem(36);
        ___qtablewidgetitem39->setText(QApplication::translate("Syn_BinCodesDlg", "37", 0));
        QTableWidgetItem *___qtablewidgetitem40 = BinCodesTableWidget->verticalHeaderItem(37);
        ___qtablewidgetitem40->setText(QApplication::translate("Syn_BinCodesDlg", "38", 0));
        QTableWidgetItem *___qtablewidgetitem41 = BinCodesTableWidget->verticalHeaderItem(38);
        ___qtablewidgetitem41->setText(QApplication::translate("Syn_BinCodesDlg", "39", 0));
        QTableWidgetItem *___qtablewidgetitem42 = BinCodesTableWidget->verticalHeaderItem(39);
        ___qtablewidgetitem42->setText(QApplication::translate("Syn_BinCodesDlg", "40", 0));
        QTableWidgetItem *___qtablewidgetitem43 = BinCodesTableWidget->verticalHeaderItem(40);
        ___qtablewidgetitem43->setText(QApplication::translate("Syn_BinCodesDlg", "41", 0));
        QTableWidgetItem *___qtablewidgetitem44 = BinCodesTableWidget->verticalHeaderItem(41);
        ___qtablewidgetitem44->setText(QApplication::translate("Syn_BinCodesDlg", "42", 0));
        QTableWidgetItem *___qtablewidgetitem45 = BinCodesTableWidget->verticalHeaderItem(42);
        ___qtablewidgetitem45->setText(QApplication::translate("Syn_BinCodesDlg", "43", 0));
        QTableWidgetItem *___qtablewidgetitem46 = BinCodesTableWidget->verticalHeaderItem(43);
        ___qtablewidgetitem46->setText(QApplication::translate("Syn_BinCodesDlg", "44", 0));
        QTableWidgetItem *___qtablewidgetitem47 = BinCodesTableWidget->verticalHeaderItem(44);
        ___qtablewidgetitem47->setText(QApplication::translate("Syn_BinCodesDlg", "45", 0));
        QTableWidgetItem *___qtablewidgetitem48 = BinCodesTableWidget->verticalHeaderItem(45);
        ___qtablewidgetitem48->setText(QApplication::translate("Syn_BinCodesDlg", "46", 0));
        QTableWidgetItem *___qtablewidgetitem49 = BinCodesTableWidget->verticalHeaderItem(46);
        ___qtablewidgetitem49->setText(QApplication::translate("Syn_BinCodesDlg", "47", 0));
        QTableWidgetItem *___qtablewidgetitem50 = BinCodesTableWidget->verticalHeaderItem(47);
        ___qtablewidgetitem50->setText(QApplication::translate("Syn_BinCodesDlg", "48", 0));
        QTableWidgetItem *___qtablewidgetitem51 = BinCodesTableWidget->verticalHeaderItem(48);
        ___qtablewidgetitem51->setText(QApplication::translate("Syn_BinCodesDlg", "49", 0));
        QTableWidgetItem *___qtablewidgetitem52 = BinCodesTableWidget->verticalHeaderItem(49);
        ___qtablewidgetitem52->setText(QApplication::translate("Syn_BinCodesDlg", "50", 0));
        QTableWidgetItem *___qtablewidgetitem53 = BinCodesTableWidget->verticalHeaderItem(50);
        ___qtablewidgetitem53->setText(QApplication::translate("Syn_BinCodesDlg", "51", 0));
        QTableWidgetItem *___qtablewidgetitem54 = BinCodesTableWidget->verticalHeaderItem(51);
        ___qtablewidgetitem54->setText(QApplication::translate("Syn_BinCodesDlg", "52", 0));
        QTableWidgetItem *___qtablewidgetitem55 = BinCodesTableWidget->verticalHeaderItem(52);
        ___qtablewidgetitem55->setText(QApplication::translate("Syn_BinCodesDlg", "53", 0));
        QTableWidgetItem *___qtablewidgetitem56 = BinCodesTableWidget->verticalHeaderItem(53);
        ___qtablewidgetitem56->setText(QApplication::translate("Syn_BinCodesDlg", "54", 0));
        QTableWidgetItem *___qtablewidgetitem57 = BinCodesTableWidget->verticalHeaderItem(54);
        ___qtablewidgetitem57->setText(QApplication::translate("Syn_BinCodesDlg", "55", 0));
        QTableWidgetItem *___qtablewidgetitem58 = BinCodesTableWidget->verticalHeaderItem(55);
        ___qtablewidgetitem58->setText(QApplication::translate("Syn_BinCodesDlg", "56", 0));
        QTableWidgetItem *___qtablewidgetitem59 = BinCodesTableWidget->verticalHeaderItem(56);
        ___qtablewidgetitem59->setText(QApplication::translate("Syn_BinCodesDlg", "57", 0));
        QTableWidgetItem *___qtablewidgetitem60 = BinCodesTableWidget->verticalHeaderItem(57);
        ___qtablewidgetitem60->setText(QApplication::translate("Syn_BinCodesDlg", "58", 0));

        const bool __sortingEnabled = BinCodesTableWidget->isSortingEnabled();
        BinCodesTableWidget->setSortingEnabled(false);
        QTableWidgetItem *___qtablewidgetitem61 = BinCodesTableWidget->item(0, 0);
        ___qtablewidgetitem61->setText(QApplication::translate("Syn_BinCodesDlg", "1", 0));
        QTableWidgetItem *___qtablewidgetitem62 = BinCodesTableWidget->item(0, 2);
        ___qtablewidgetitem62->setText(QApplication::translate("Syn_BinCodesDlg", "Pass", 0));
        QTableWidgetItem *___qtablewidgetitem63 = BinCodesTableWidget->item(1, 0);
        ___qtablewidgetitem63->setText(QApplication::translate("Syn_BinCodesDlg", "100", 0));
        QTableWidgetItem *___qtablewidgetitem64 = BinCodesTableWidget->item(1, 1);
        ___qtablewidgetitem64->setText(QApplication::translate("Syn_BinCodesDlg", "SPI Comm check", 0));
        QTableWidgetItem *___qtablewidgetitem65 = BinCodesTableWidget->item(1, 2);
        ___qtablewidgetitem65->setText(QApplication::translate("Syn_BinCodesDlg", "Excutes the Get_Version command(0x01) and compares the FW buildnum value with the expected value", 0));
        QTableWidgetItem *___qtablewidgetitem66 = BinCodesTableWidget->item(2, 0);
        ___qtablewidgetitem66->setText(QApplication::translate("Syn_BinCodesDlg", "101", 0));
        QTableWidgetItem *___qtablewidgetitem67 = BinCodesTableWidget->item(2, 2);
        ___qtablewidgetitem67->setText(QApplication::translate("Syn_BinCodesDlg", "Un used", 0));
        QTableWidgetItem *___qtablewidgetitem68 = BinCodesTableWidget->item(3, 0);
        ___qtablewidgetitem68->setText(QApplication::translate("Syn_BinCodesDlg", "102", 0));
        QTableWidgetItem *___qtablewidgetitem69 = BinCodesTableWidget->item(3, 1);
        ___qtablewidgetitem69->setText(QApplication::translate("Syn_BinCodesDlg", "OSC Trim", 0));
        QTableWidgetItem *___qtablewidgetitem70 = BinCodesTableWidget->item(3, 2);
        ___qtablewidgetitem70->setText(QApplication::translate("Syn_BinCodesDlg", "Calibrate ASIC oscillaator", 0));
        QTableWidgetItem *___qtablewidgetitem71 = BinCodesTableWidget->item(4, 0);
        ___qtablewidgetitem71->setText(QApplication::translate("Syn_BinCodesDlg", "103", 0));
        QTableWidgetItem *___qtablewidgetitem72 = BinCodesTableWidget->item(4, 1);
        ___qtablewidgetitem72->setText(QApplication::translate("Syn_BinCodesDlg", "Slow OSC Trim", 0));
        QTableWidgetItem *___qtablewidgetitem73 = BinCodesTableWidget->item(4, 2);
        ___qtablewidgetitem73->setText(QApplication::translate("Syn_BinCodesDlg", "Calibrate ASIC digital oscillaator", 0));
        QTableWidgetItem *___qtablewidgetitem74 = BinCodesTableWidget->item(5, 0);
        ___qtablewidgetitem74->setText(QApplication::translate("Syn_BinCodesDlg", "104", 0));
        QTableWidgetItem *___qtablewidgetitem75 = BinCodesTableWidget->item(5, 1);
        ___qtablewidgetitem75->setText(QApplication::translate("Syn_BinCodesDlg", "DRDY Pin Test", 0));
        QTableWidgetItem *___qtablewidgetitem76 = BinCodesTableWidget->item(5, 2);
        ___qtablewidgetitem76->setText(QApplication::translate("Syn_BinCodesDlg", "Test DRDY pin for open/short", 0));
        QTableWidgetItem *___qtablewidgetitem77 = BinCodesTableWidget->item(6, 0);
        ___qtablewidgetitem77->setText(QApplication::translate("Syn_BinCodesDlg", "105", 0));
        QTableWidgetItem *___qtablewidgetitem78 = BinCodesTableWidget->item(6, 1);
        ___qtablewidgetitem78->setText(QApplication::translate("Syn_BinCodesDlg", "Invalidate Extended Tags", 0));
        QTableWidgetItem *___qtablewidgetitem79 = BinCodesTableWidget->item(6, 2);
        ___qtablewidgetitem79->setText(QApplication::translate("Syn_BinCodesDlg", "Invalidate any unwanted tag burned into the MainSector of the OTPROM.Typically used to invalidate incorrect AFE calibration values", 0));
        QTableWidgetItem *___qtablewidgetitem80 = BinCodesTableWidget->item(7, 0);
        ___qtablewidgetitem80->setText(QApplication::translate("Syn_BinCodesDlg", "106", 0));
        QTableWidgetItem *___qtablewidgetitem81 = BinCodesTableWidget->item(7, 1);
        ___qtablewidgetitem81->setText(QApplication::translate("Syn_BinCodesDlg", "OTPROM Boot Sector", 0));
        QTableWidgetItem *___qtablewidgetitem82 = BinCodesTableWidget->item(7, 2);
        ___qtablewidgetitem82->setText(QApplication::translate("Syn_BinCodesDlg", "Read/Write", 0));
        QTableWidgetItem *___qtablewidgetitem83 = BinCodesTableWidget->item(8, 0);
        ___qtablewidgetitem83->setText(QApplication::translate("Syn_BinCodesDlg", "107", 0));
        QTableWidgetItem *___qtablewidgetitem84 = BinCodesTableWidget->item(8, 1);
        ___qtablewidgetitem84->setText(QApplication::translate("Syn_BinCodesDlg", "Tx/Rx Opens and Shorts Tests", 0));
        QTableWidgetItem *___qtablewidgetitem85 = BinCodesTableWidget->item(8, 2);
        ___qtablewidgetitem85->setText(QApplication::translate("Syn_BinCodesDlg", "Rx&Tx opens,Rx-Tx,Tx-Gnd,Rx-Vdd,Tx-Vdd shorts for modules", 0));
        QTableWidgetItem *___qtablewidgetitem86 = BinCodesTableWidget->item(9, 0);
        ___qtablewidgetitem86->setText(QApplication::translate("Syn_BinCodesDlg", "108", 0));
        QTableWidgetItem *___qtablewidgetitem87 = BinCodesTableWidget->item(9, 1);
        ___qtablewidgetitem87->setText(QApplication::translate("Syn_BinCodesDlg", "1st Stage/2nd Stage Offset Calibration", 0));
        QTableWidgetItem *___qtablewidgetitem88 = BinCodesTableWidget->item(9, 2);
        ___qtablewidgetitem88->setText(QApplication::translate("Syn_BinCodesDlg", "Turn first and second stages of AFE to center thr ADC response close to midpoint(128)", 0));
        QTableWidgetItem *___qtablewidgetitem89 = BinCodesTableWidget->item(10, 0);
        ___qtablewidgetitem89->setText(QApplication::translate("Syn_BinCodesDlg", "109", 0));
        QTableWidgetItem *___qtablewidgetitem90 = BinCodesTableWidget->item(10, 1);
        ___qtablewidgetitem90->setText(QApplication::translate("Syn_BinCodesDlg", "Button Test", 0));
        QTableWidgetItem *___qtablewidgetitem91 = BinCodesTableWidget->item(10, 2);
        ___qtablewidgetitem91->setText(QApplication::translate("Syn_BinCodesDlg", "Check for open/short of the button", 0));
        QTableWidgetItem *___qtablewidgetitem92 = BinCodesTableWidget->item(11, 0);
        ___qtablewidgetitem92->setText(QApplication::translate("Syn_BinCodesDlg", "110", 0));
        QTableWidgetItem *___qtablewidgetitem93 = BinCodesTableWidget->item(11, 1);
        ___qtablewidgetitem93->setText(QApplication::translate("Syn_BinCodesDlg", "Image-Pegged Pixel Test Row/Column", 0));
        QTableWidgetItem *___qtablewidgetitem94 = BinCodesTableWidget->item(11, 2);
        ___qtablewidgetitem94->setText(QApplication::translate("Syn_BinCodesDlg", "Check that pixels have enough head room to provide good performance", 0));
        QTableWidgetItem *___qtablewidgetitem95 = BinCodesTableWidget->item(12, 0);
        ___qtablewidgetitem95->setText(QApplication::translate("Syn_BinCodesDlg", "111", 0));
        QTableWidgetItem *___qtablewidgetitem96 = BinCodesTableWidget->item(12, 1);
        ___qtablewidgetitem96->setText(QApplication::translate("Syn_BinCodesDlg", "Image-Floored Pixel Test Row/Column", 0));
        QTableWidgetItem *___qtablewidgetitem97 = BinCodesTableWidget->item(12, 2);
        ___qtablewidgetitem97->setText(QApplication::translate("Syn_BinCodesDlg", "Check that pixels have enough foot room to provide good performance", 0));
        QTableWidgetItem *___qtablewidgetitem98 = BinCodesTableWidget->item(13, 0);
        ___qtablewidgetitem98->setText(QApplication::translate("Syn_BinCodesDlg", "112", 0));
        QTableWidgetItem *___qtablewidgetitem99 = BinCodesTableWidget->item(13, 1);
        ___qtablewidgetitem99->setText(QApplication::translate("Syn_BinCodesDlg", "Image-Consecutive Pegged Pixel Test Row/Column", 0));
        QTableWidgetItem *___qtablewidgetitem100 = BinCodesTableWidget->item(13, 2);
        ___qtablewidgetitem100->setText(QApplication::translate("Syn_BinCodesDlg", "Check that less than a cetain amout of consecutive pixels have enough head room to provide good performance to the Matcher", 0));
        QTableWidgetItem *___qtablewidgetitem101 = BinCodesTableWidget->item(14, 0);
        ___qtablewidgetitem101->setText(QApplication::translate("Syn_BinCodesDlg", "113", 0));
        QTableWidgetItem *___qtablewidgetitem102 = BinCodesTableWidget->item(14, 1);
        ___qtablewidgetitem102->setText(QApplication::translate("Syn_BinCodesDlg", "Image-Consecutive Floored Pixel Test Row/Column", 0));
        QTableWidgetItem *___qtablewidgetitem103 = BinCodesTableWidget->item(14, 2);
        ___qtablewidgetitem103->setText(QApplication::translate("Syn_BinCodesDlg", "Check that less than a cetain amout of consecutive pixels have enough foot room to provide good performance to the Matcher", 0));
        QTableWidgetItem *___qtablewidgetitem104 = BinCodesTableWidget->item(15, 0);
        ___qtablewidgetitem104->setText(QApplication::translate("Syn_BinCodesDlg", "114", 0));
        QTableWidgetItem *___qtablewidgetitem105 = BinCodesTableWidget->item(15, 1);
        ___qtablewidgetitem105->setText(QApplication::translate("Syn_BinCodesDlg", "Delta Pixel Row/Column", 0));
        QTableWidgetItem *___qtablewidgetitem106 = BinCodesTableWidget->item(15, 2);
        ___qtablewidgetitem106->setText(QApplication::translate("Syn_BinCodesDlg", "Check for changes on each pixel with and without finger", 0));
        QTableWidgetItem *___qtablewidgetitem107 = BinCodesTableWidget->item(16, 0);
        ___qtablewidgetitem107->setText(QApplication::translate("Syn_BinCodesDlg", "115", 0));
        QTableWidgetItem *___qtablewidgetitem108 = BinCodesTableWidget->item(16, 1);
        ___qtablewidgetitem108->setText(QApplication::translate("Syn_BinCodesDlg", "Current-Imaging", 0));
        QTableWidgetItem *___qtablewidgetitem109 = BinCodesTableWidget->item(16, 2);
        ___qtablewidgetitem109->setText(QApplication::translate("Syn_BinCodesDlg", "Check current while acquiring an image", 0));
        QTableWidgetItem *___qtablewidgetitem110 = BinCodesTableWidget->item(17, 0);
        ___qtablewidgetitem110->setText(QApplication::translate("Syn_BinCodesDlg", "116", 0));
        QTableWidgetItem *___qtablewidgetitem111 = BinCodesTableWidget->item(17, 1);
        ___qtablewidgetitem111->setText(QApplication::translate("Syn_BinCodesDlg", "Current-WOE", 0));
        QTableWidgetItem *___qtablewidgetitem112 = BinCodesTableWidget->item(17, 2);
        ___qtablewidgetitem112->setText(QApplication::translate("Syn_BinCodesDlg", "Check current while module is Idle", 0));
        QTableWidgetItem *___qtablewidgetitem113 = BinCodesTableWidget->item(18, 0);
        ___qtablewidgetitem113->setText(QApplication::translate("Syn_BinCodesDlg", "117", 0));
        QTableWidgetItem *___qtablewidgetitem114 = BinCodesTableWidget->item(18, 1);
        ___qtablewidgetitem114->setText(QApplication::translate("Syn_BinCodesDlg", "Current-WOF/WoVar", 0));
        QTableWidgetItem *___qtablewidgetitem115 = BinCodesTableWidget->item(18, 2);
        ___qtablewidgetitem115->setText(QApplication::translate("Syn_BinCodesDlg", "Check current for wake on finger or variance mode", 0));
        QTableWidgetItem *___qtablewidgetitem116 = BinCodesTableWidget->item(19, 0);
        ___qtablewidgetitem116->setText(QApplication::translate("Syn_BinCodesDlg", "117.1", 0));
        QTableWidgetItem *___qtablewidgetitem117 = BinCodesTableWidget->item(19, 1);
        ___qtablewidgetitem117->setText(QApplication::translate("Syn_BinCodesDlg", "Current-WOF-Low Power", 0));
        QTableWidgetItem *___qtablewidgetitem118 = BinCodesTableWidget->item(19, 2);
        ___qtablewidgetitem118->setText(QApplication::translate("Syn_BinCodesDlg", "Check current for wake at low power", 0));
        QTableWidgetItem *___qtablewidgetitem119 = BinCodesTableWidget->item(20, 0);
        ___qtablewidgetitem119->setText(QApplication::translate("Syn_BinCodesDlg", "118", 0));
        QTableWidgetItem *___qtablewidgetitem120 = BinCodesTableWidget->item(20, 1);
        ___qtablewidgetitem120->setText(QApplication::translate("Syn_BinCodesDlg", "Current-Sleep", 0));
        QTableWidgetItem *___qtablewidgetitem121 = BinCodesTableWidget->item(20, 2);
        ___qtablewidgetitem121->setText(QApplication::translate("Syn_BinCodesDlg", "Check current while the module is in Sleep mode", 0));
        QTableWidgetItem *___qtablewidgetitem122 = BinCodesTableWidget->item(21, 0);
        ___qtablewidgetitem122->setText(QApplication::translate("Syn_BinCodesDlg", "119", 0));
        QTableWidgetItem *___qtablewidgetitem123 = BinCodesTableWidget->item(21, 1);
        ___qtablewidgetitem123->setText(QApplication::translate("Syn_BinCodesDlg", "SNR Test", 0));
        QTableWidgetItem *___qtablewidgetitem124 = BinCodesTableWidget->item(21, 2);
        ___qtablewidgetitem124->setText(QApplication::translate("Syn_BinCodesDlg", "Using a fake finger,calculate the SNR of different zones,as well as for the overall sensor area(SNR,Single and Noise)", 0));
        QTableWidgetItem *___qtablewidgetitem125 = BinCodesTableWidget->item(22, 0);
        ___qtablewidgetitem125->setText(QApplication::translate("Syn_BinCodesDlg", "120", 0));
        QTableWidgetItem *___qtablewidgetitem126 = BinCodesTableWidget->item(22, 1);
        ___qtablewidgetitem126->setText(QApplication::translate("Syn_BinCodesDlg", "Pixel Uniformity", 0));
        QTableWidgetItem *___qtablewidgetitem127 = BinCodesTableWidget->item(22, 2);
        ___qtablewidgetitem127->setText(QApplication::translate("Syn_BinCodesDlg", "Checking for sensor trace abnormalities,i.r. under/over etching of coopertraces", 0));
        QTableWidgetItem *___qtablewidgetitem128 = BinCodesTableWidget->item(23, 0);
        ___qtablewidgetitem128->setText(QApplication::translate("Syn_BinCodesDlg", "120.1", 0));
        QTableWidgetItem *___qtablewidgetitem129 = BinCodesTableWidget->item(23, 1);
        ___qtablewidgetitem129->setText(QApplication::translate("Syn_BinCodesDlg", "SDK Baseline test failure", 0));
        QTableWidgetItem *___qtablewidgetitem130 = BinCodesTableWidget->item(23, 2);
        ___qtablewidgetitem130->setText(QApplication::translate("Syn_BinCodesDlg", "SDK Baseline test failure", 0));
        QTableWidgetItem *___qtablewidgetitem131 = BinCodesTableWidget->item(24, 0);
        ___qtablewidgetitem131->setText(QApplication::translate("Syn_BinCodesDlg", "121", 0));
        QTableWidgetItem *___qtablewidgetitem132 = BinCodesTableWidget->item(24, 1);
        ___qtablewidgetitem132->setText(QApplication::translate("Syn_BinCodesDlg", "FW Upgrade/bug fix patch write", 0));
        QTableWidgetItem *___qtablewidgetitem133 = BinCodesTableWidget->item(24, 2);
        ___qtablewidgetitem133->setText(QApplication::translate("Syn_BinCodesDlg", "OTPROM Write thes updates and verify", 0));
        QTableWidgetItem *___qtablewidgetitem134 = BinCodesTableWidget->item(25, 0);
        ___qtablewidgetitem134->setText(QApplication::translate("Syn_BinCodesDlg", "122", 0));
        QTableWidgetItem *___qtablewidgetitem135 = BinCodesTableWidget->item(25, 1);
        ___qtablewidgetitem135->setText(QApplication::translate("Syn_BinCodesDlg", "Security patch write", 0));
        QTableWidgetItem *___qtablewidgetitem136 = BinCodesTableWidget->item(25, 2);
        ___qtablewidgetitem136->setText(QApplication::translate("Syn_BinCodesDlg", "OTPROM Write thes updates and verify", 0));
        QTableWidgetItem *___qtablewidgetitem137 = BinCodesTableWidget->item(26, 0);
        ___qtablewidgetitem137->setText(QApplication::translate("Syn_BinCodesDlg", "123", 0));
        QTableWidgetItem *___qtablewidgetitem138 = BinCodesTableWidget->item(26, 1);
        ___qtablewidgetitem138->setText(QApplication::translate("Syn_BinCodesDlg", "Serial Number", 0));
        QTableWidgetItem *___qtablewidgetitem139 = BinCodesTableWidget->item(26, 2);
        ___qtablewidgetitem139->setText(QApplication::translate("Syn_BinCodesDlg", "Read back or Issuing new number", 0));
        QTableWidgetItem *___qtablewidgetitem140 = BinCodesTableWidget->item(27, 0);
        ___qtablewidgetitem140->setText(QApplication::translate("Syn_BinCodesDlg", "124", 0));
        QTableWidgetItem *___qtablewidgetitem141 = BinCodesTableWidget->item(27, 1);
        ___qtablewidgetitem141->setText(QApplication::translate("Syn_BinCodesDlg", "ProductID", 0));
        QTableWidgetItem *___qtablewidgetitem142 = BinCodesTableWidget->item(27, 2);
        ___qtablewidgetitem142->setText(QApplication::translate("Syn_BinCodesDlg", "Incorrect ProductID", 0));
        QTableWidgetItem *___qtablewidgetitem143 = BinCodesTableWidget->item(28, 0);
        ___qtablewidgetitem143->setText(QApplication::translate("Syn_BinCodesDlg", "125", 0));
        QTableWidgetItem *___qtablewidgetitem144 = BinCodesTableWidget->item(28, 1);
        ___qtablewidgetitem144->setText(QApplication::translate("Syn_BinCodesDlg", "OTPROM Main Sector", 0));
        QTableWidgetItem *___qtablewidgetitem145 = BinCodesTableWidget->item(28, 2);
        ___qtablewidgetitem145->setText(QApplication::translate("Syn_BinCodesDlg", "Read/Write", 0));
        QTableWidgetItem *___qtablewidgetitem146 = BinCodesTableWidget->item(29, 0);
        ___qtablewidgetitem146->setText(QApplication::translate("Syn_BinCodesDlg", "126", 0));
        QTableWidgetItem *___qtablewidgetitem147 = BinCodesTableWidget->item(29, 1);
        ___qtablewidgetitem147->setText(QApplication::translate("Syn_BinCodesDlg", "Sharpness Test", 0));
        QTableWidgetItem *___qtablewidgetitem148 = BinCodesTableWidget->item(29, 2);
        ___qtablewidgetitem148->setText(QApplication::translate("Syn_BinCodesDlg", "Test for uneven/fuzzy Fake Finger Image", 0));
        QTableWidgetItem *___qtablewidgetitem149 = BinCodesTableWidget->item(30, 0);
        ___qtablewidgetitem149->setText(QApplication::translate("Syn_BinCodesDlg", "127", 0));
        QTableWidgetItem *___qtablewidgetitem150 = BinCodesTableWidget->item(30, 1);
        ___qtablewidgetitem150->setText(QApplication::translate("Syn_BinCodesDlg", "Laplacian", 0));
        QTableWidgetItem *___qtablewidgetitem151 = BinCodesTableWidget->item(30, 2);
        ___qtablewidgetitem151->setText(QApplication::translate("Syn_BinCodesDlg", "Test for Distorted Fake Finger Image", 0));
        QTableWidgetItem *___qtablewidgetitem152 = BinCodesTableWidget->item(31, 0);
        ___qtablewidgetitem152->setText(QApplication::translate("Syn_BinCodesDlg", "128", 0));
        QTableWidgetItem *___qtablewidgetitem153 = BinCodesTableWidget->item(31, 1);
        ___qtablewidgetitem153->setText(QApplication::translate("Syn_BinCodesDlg", "Stdev of RXs", 0));
        QTableWidgetItem *___qtablewidgetitem154 = BinCodesTableWidget->item(31, 2);
        ___qtablewidgetitem154->setText(QApplication::translate("Syn_BinCodesDlg", "Tests for uneven Rx response to Fake Finger ", 0));
        QTableWidgetItem *___qtablewidgetitem155 = BinCodesTableWidget->item(32, 0);
        ___qtablewidgetitem155->setText(QApplication::translate("Syn_BinCodesDlg", "129", 0));
        QTableWidgetItem *___qtablewidgetitem156 = BinCodesTableWidget->item(32, 1);
        ___qtablewidgetitem156->setText(QApplication::translate("Syn_BinCodesDlg", "Imperfection", 0));
        QTableWidgetItem *___qtablewidgetitem157 = BinCodesTableWidget->item(32, 2);
        ___qtablewidgetitem157->setText(QApplication::translate("Syn_BinCodesDlg", "Tests for Imperfect image response to Fake Finger ", 0));
        QTableWidgetItem *___qtablewidgetitem158 = BinCodesTableWidget->item(33, 0);
        ___qtablewidgetitem158->setText(QApplication::translate("Syn_BinCodesDlg", "130", 0));
        QTableWidgetItem *___qtablewidgetitem159 = BinCodesTableWidget->item(33, 1);
        ___qtablewidgetitem159->setText(QApplication::translate("Syn_BinCodesDlg", "DutCtrlComm", 0));
        QTableWidgetItem *___qtablewidgetitem160 = BinCodesTableWidget->item(33, 2);
        ___qtablewidgetitem160->setText(QApplication::translate("Syn_BinCodesDlg", "DUT Cotroller is not communicating properly", 0));
        QTableWidgetItem *___qtablewidgetitem161 = BinCodesTableWidget->item(34, 0);
        ___qtablewidgetitem161->setText(QApplication::translate("Syn_BinCodesDlg", "131", 0));
        QTableWidgetItem *___qtablewidgetitem162 = BinCodesTableWidget->item(34, 1);
        ___qtablewidgetitem162->setText(QApplication::translate("Syn_BinCodesDlg", "WOF", 0));
        QTableWidgetItem *___qtablewidgetitem163 = BinCodesTableWidget->item(34, 2);
        ___qtablewidgetitem163->setText(QApplication::translate("Syn_BinCodesDlg", "Check the delta with finger and without finger", 0));
        QTableWidgetItem *___qtablewidgetitem164 = BinCodesTableWidget->item(35, 0);
        ___qtablewidgetitem164->setText(QApplication::translate("Syn_BinCodesDlg", "132", 0));
        QTableWidgetItem *___qtablewidgetitem165 = BinCodesTableWidget->item(35, 1);
        ___qtablewidgetitem165->setText(QApplication::translate("Syn_BinCodesDlg", "Extended Tag", 0));
        QTableWidgetItem *___qtablewidgetitem166 = BinCodesTableWidget->item(35, 2);
        ___qtablewidgetitem166->setText(QApplication::translate("Syn_BinCodesDlg", "Extended Tags are not all available", 0));
        QTableWidgetItem *___qtablewidgetitem167 = BinCodesTableWidget->item(36, 0);
        ___qtablewidgetitem167->setText(QApplication::translate("Syn_BinCodesDlg", "133", 0));
        QTableWidgetItem *___qtablewidgetitem168 = BinCodesTableWidget->item(36, 1);
        ___qtablewidgetitem168->setText(QApplication::translate("Syn_BinCodesDlg", "Pixel Uniformity Patch", 0));
        QTableWidgetItem *___qtablewidgetitem169 = BinCodesTableWidget->item(36, 2);
        ___qtablewidgetitem169->setText(QApplication::translate("Syn_BinCodesDlg", "Checking for sensor trace abnormalities using test patch", 0));
        QTableWidgetItem *___qtablewidgetitem170 = BinCodesTableWidget->item(37, 0);
        ___qtablewidgetitem170->setText(QApplication::translate("Syn_BinCodesDlg", "134", 0));
        QTableWidgetItem *___qtablewidgetitem171 = BinCodesTableWidget->item(37, 1);
        ___qtablewidgetitem171->setText(QApplication::translate("Syn_BinCodesDlg", "DUT timeout error", 0));
        QTableWidgetItem *___qtablewidgetitem172 = BinCodesTableWidget->item(37, 2);
        ___qtablewidgetitem172->setText(QApplication::translate("Syn_BinCodesDlg", "When communicating with the DUT,the command protocol was not as expected", 0));
        QTableWidgetItem *___qtablewidgetitem173 = BinCodesTableWidget->item(38, 0);
        ___qtablewidgetitem173->setText(QApplication::translate("Syn_BinCodesDlg", "135", 0));
        QTableWidgetItem *___qtablewidgetitem174 = BinCodesTableWidget->item(38, 1);
        ___qtablewidgetitem174->setText(QApplication::translate("Syn_BinCodesDlg", "WOVAR", 0));
        QTableWidgetItem *___qtablewidgetitem175 = BinCodesTableWidget->item(39, 0);
        ___qtablewidgetitem175->setText(QApplication::translate("Syn_BinCodesDlg", "136", 0));
        QTableWidgetItem *___qtablewidgetitem176 = BinCodesTableWidget->item(39, 1);
        ___qtablewidgetitem176->setText(QApplication::translate("Syn_BinCodesDlg", "RAM Test", 0));
        QTableWidgetItem *___qtablewidgetitem177 = BinCodesTableWidget->item(39, 2);
        ___qtablewidgetitem177->setText(QApplication::translate("Syn_BinCodesDlg", "Test patchs return errors in the RAM", 0));
        QTableWidgetItem *___qtablewidgetitem178 = BinCodesTableWidget->item(40, 0);
        ___qtablewidgetitem178->setText(QApplication::translate("Syn_BinCodesDlg", "137", 0));
        QTableWidgetItem *___qtablewidgetitem179 = BinCodesTableWidget->item(40, 1);
        ___qtablewidgetitem179->setText(QApplication::translate("Syn_BinCodesDlg", "Build # Mismatch", 0));
        QTableWidgetItem *___qtablewidgetitem180 = BinCodesTableWidget->item(40, 2);
        ___qtablewidgetitem180->setText(QApplication::translate("Syn_BinCodesDlg", "The sensor returns a Build # that is not equal to that specified in the Initialization step's argurment list", 0));
        QTableWidgetItem *___qtablewidgetitem181 = BinCodesTableWidget->item(41, 0);
        ___qtablewidgetitem181->setText(QApplication::translate("Syn_BinCodesDlg", "138", 0));
        QTableWidgetItem *___qtablewidgetitem182 = BinCodesTableWidget->item(41, 1);
        ___qtablewidgetitem182->setText(QApplication::translate("Syn_BinCodesDlg", "LED Test", 0));
        QTableWidgetItem *___qtablewidgetitem183 = BinCodesTableWidget->item(41, 2);
        ___qtablewidgetitem183->setText(QApplication::translate("Syn_BinCodesDlg", "Check to assure LED(s) are functional", 0));
        QTableWidgetItem *___qtablewidgetitem184 = BinCodesTableWidget->item(42, 0);
        ___qtablewidgetitem184->setText(QApplication::translate("Syn_BinCodesDlg", "139", 0));
        QTableWidgetItem *___qtablewidgetitem185 = BinCodesTableWidget->item(42, 1);
        ___qtablewidgetitem185->setText(QApplication::translate("Syn_BinCodesDlg", "USB Comm", 0));
        QTableWidgetItem *___qtablewidgetitem186 = BinCodesTableWidget->item(42, 2);
        ___qtablewidgetitem186->setText(QApplication::translate("Syn_BinCodesDlg", "USB comm check fails to enumerate", 0));
        QTableWidgetItem *___qtablewidgetitem187 = BinCodesTableWidget->item(43, 0);
        ___qtablewidgetitem187->setText(QApplication::translate("Syn_BinCodesDlg", "140", 0));
        QTableWidgetItem *___qtablewidgetitem188 = BinCodesTableWidget->item(43, 1);
        ___qtablewidgetitem188->setText(QApplication::translate("Syn_BinCodesDlg", "PGA OTP Variance Score", 0));
        QTableWidgetItem *___qtablewidgetitem189 = BinCodesTableWidget->item(43, 2);
        ___qtablewidgetitem189->setText(QApplication::translate("Syn_BinCodesDlg", "Stage2 - 5 lines variance", 0));
        QTableWidgetItem *___qtablewidgetitem190 = BinCodesTableWidget->item(44, 0);
        ___qtablewidgetitem190->setText(QApplication::translate("Syn_BinCodesDlg", "141", 0));
        QTableWidgetItem *___qtablewidgetitem191 = BinCodesTableWidget->item(44, 1);
        ___qtablewidgetitem191->setText(QApplication::translate("Syn_BinCodesDlg", "MS0 Tag Checksum Failure", 0));
        QTableWidgetItem *___qtablewidgetitem192 = BinCodesTableWidget->item(44, 2);
        ___qtablewidgetitem192->setText(QApplication::translate("Syn_BinCodesDlg", "The checksum of one or more records stored in MS0 is erroneous", 0));
        QTableWidgetItem *___qtablewidgetitem193 = BinCodesTableWidget->item(45, 0);
        ___qtablewidgetitem193->setText(QApplication::translate("Syn_BinCodesDlg", "142", 0));
        QTableWidgetItem *___qtablewidgetitem194 = BinCodesTableWidget->item(45, 1);
        ___qtablewidgetitem194->setText(QApplication::translate("Syn_BinCodesDlg", "AFE Matching Patch", 0));
        QTableWidgetItem *___qtablewidgetitem195 = BinCodesTableWidget->item(45, 2);
        ___qtablewidgetitem195->setText(QApplication::translate("Syn_BinCodesDlg", "AFE Match/Balance Testing", 0));
        QTableWidgetItem *___qtablewidgetitem196 = BinCodesTableWidget->item(46, 0);
        ___qtablewidgetitem196->setText(QApplication::translate("Syn_BinCodesDlg", "143", 0));
        QTableWidgetItem *___qtablewidgetitem197 = BinCodesTableWidget->item(46, 1);
        ___qtablewidgetitem197->setText(QApplication::translate("Syn_BinCodesDlg", "Voltage mismatch", 0));
        QTableWidgetItem *___qtablewidgetitem198 = BinCodesTableWidget->item(46, 2);
        ___qtablewidgetitem198->setText(QApplication::translate("Syn_BinCodesDlg", "The Voltages at which the ADC Baseline readins obtained do not match those used during the current test ", 0));
        QTableWidgetItem *___qtablewidgetitem199 = BinCodesTableWidget->item(47, 0);
        ___qtablewidgetitem199->setText(QApplication::translate("Syn_BinCodesDlg", "144", 0));
        QTableWidgetItem *___qtablewidgetitem200 = BinCodesTableWidget->item(47, 1);
        ___qtablewidgetitem200->setText(QApplication::translate("Syn_BinCodesDlg", "Premature sensor removal", 0));
        QTableWidgetItem *___qtablewidgetitem201 = BinCodesTableWidget->item(47, 2);
        ___qtablewidgetitem201->setText(QApplication::translate("Syn_BinCodesDlg", "The operator has removed the sensor before the completion of scoring test", 0));
        QTableWidgetItem *___qtablewidgetitem202 = BinCodesTableWidget->item(48, 0);
        ___qtablewidgetitem202->setText(QApplication::translate("Syn_BinCodesDlg", "145", 0));
        QTableWidgetItem *___qtablewidgetitem203 = BinCodesTableWidget->item(48, 1);
        ___qtablewidgetitem203->setText(QApplication::translate("Syn_BinCodesDlg", "Layer ID Test", 0));
        QTableWidgetItem *___qtablewidgetitem204 = BinCodesTableWidget->item(48, 2);
        ___qtablewidgetitem204->setText(QApplication::translate("Syn_BinCodesDlg", "Test patch has found Layer ID error", 0));
        QTableWidgetItem *___qtablewidgetitem205 = BinCodesTableWidget->item(49, 0);
        ___qtablewidgetitem205->setText(QApplication::translate("Syn_BinCodesDlg", "146", 0));
        QTableWidgetItem *___qtablewidgetitem206 = BinCodesTableWidget->item(49, 1);
        ___qtablewidgetitem206->setText(QApplication::translate("Syn_BinCodesDlg", "Flex ID Test", 0));
        QTableWidgetItem *___qtablewidgetitem207 = BinCodesTableWidget->item(49, 2);
        ___qtablewidgetitem207->setText(QApplication::translate("Syn_BinCodesDlg", "Test patch has found Flex ID error", 0));
        QTableWidgetItem *___qtablewidgetitem208 = BinCodesTableWidget->item(50, 0);
        ___qtablewidgetitem208->setText(QApplication::translate("Syn_BinCodesDlg", "147", 0));
        QTableWidgetItem *___qtablewidgetitem209 = BinCodesTableWidget->item(50, 1);
        ___qtablewidgetitem209->setText(QApplication::translate("Syn_BinCodesDlg", "Configuration file anomaly", 0));
        QTableWidgetItem *___qtablewidgetitem210 = BinCodesTableWidget->item(50, 2);
        ___qtablewidgetitem210->setText(QApplication::translate("Syn_BinCodesDlg", "A problem was detected in the specified configuration file", 0));
        QTableWidgetItem *___qtablewidgetitem211 = BinCodesTableWidget->item(51, 0);
        ___qtablewidgetitem211->setText(QApplication::translate("Syn_BinCodesDlg", "148", 0));
        QTableWidgetItem *___qtablewidgetitem212 = BinCodesTableWidget->item(51, 1);
        ___qtablewidgetitem212->setText(QApplication::translate("Syn_BinCodesDlg", "SPI Flash Module Failure", 0));
        QTableWidgetItem *___qtablewidgetitem213 = BinCodesTableWidget->item(51, 2);
        ___qtablewidgetitem213->setText(QApplication::translate("Syn_BinCodesDlg", "SMT failure of the SPI flash module for Match In Sensor products", 0));
        QTableWidgetItem *___qtablewidgetitem214 = BinCodesTableWidget->item(52, 0);
        ___qtablewidgetitem214->setText(QApplication::translate("Syn_BinCodesDlg", "148.1", 0));
        QTableWidgetItem *___qtablewidgetitem215 = BinCodesTableWidget->item(52, 1);
        ___qtablewidgetitem215->setText(QApplication::translate("Syn_BinCodesDlg", "SPI Ownership Failure", 0));
        QTableWidgetItem *___qtablewidgetitem216 = BinCodesTableWidget->item(52, 2);
        ___qtablewidgetitem216->setText(QApplication::translate("Syn_BinCodesDlg", "SPI Ownership Failure", 0));
        QTableWidgetItem *___qtablewidgetitem217 = BinCodesTableWidget->item(53, 0);
        ___qtablewidgetitem217->setText(QApplication::translate("Syn_BinCodesDlg", "149", 0));
        QTableWidgetItem *___qtablewidgetitem218 = BinCodesTableWidget->item(53, 1);
        ___qtablewidgetitem218->setText(QApplication::translate("Syn_BinCodesDlg", "Power Supply Failure", 0));
        QTableWidgetItem *___qtablewidgetitem219 = BinCodesTableWidget->item(53, 2);
        ___qtablewidgetitem219->setText(QApplication::translate("Syn_BinCodesDlg", "The power supplied to the DUT is not as specified in the configuration file", 0));
        QTableWidgetItem *___qtablewidgetitem220 = BinCodesTableWidget->item(54, 0);
        ___qtablewidgetitem220->setText(QApplication::translate("Syn_BinCodesDlg", "150", 0));
        QTableWidgetItem *___qtablewidgetitem221 = BinCodesTableWidget->item(54, 1);
        ___qtablewidgetitem221->setText(QApplication::translate("Syn_BinCodesDlg", "Package Type Failure", 0));
        QTableWidgetItem *___qtablewidgetitem222 = BinCodesTableWidget->item(54, 2);
        ___qtablewidgetitem222->setText(QApplication::translate("Syn_BinCodesDlg", "The package type read from OTP dose not match that specified in the config file", 0));
        QTableWidgetItem *___qtablewidgetitem223 = BinCodesTableWidget->item(55, 0);
        ___qtablewidgetitem223->setText(QApplication::translate("Syn_BinCodesDlg", "151", 0));
        QTableWidgetItem *___qtablewidgetitem224 = BinCodesTableWidget->item(55, 1);
        ___qtablewidgetitem224->setText(QApplication::translate("Syn_BinCodesDlg", "AFE Test Failure", 0));
        QTableWidgetItem *___qtablewidgetitem225 = BinCodesTableWidget->item(55, 2);
        ___qtablewidgetitem225->setText(QApplication::translate("Syn_BinCodesDlg", "AFE Test Failure", 0));
        QTableWidgetItem *___qtablewidgetitem226 = BinCodesTableWidget->item(56, 0);
        ___qtablewidgetitem226->setText(QApplication::translate("Syn_BinCodesDlg", "152", 0));
        QTableWidgetItem *___qtablewidgetitem227 = BinCodesTableWidget->item(56, 1);
        ___qtablewidgetitem227->setText(QApplication::translate("Syn_BinCodesDlg", "BootSector Fail", 0));
        QTableWidgetItem *___qtablewidgetitem228 = BinCodesTableWidget->item(57, 0);
        ___qtablewidgetitem228->setText(QApplication::translate("Syn_BinCodesDlg", "153", 0));
        QTableWidgetItem *___qtablewidgetitem229 = BinCodesTableWidget->item(57, 1);
        ___qtablewidgetitem229->setText(QApplication::translate("Syn_BinCodesDlg", "MainSector Fail", 0));
        BinCodesTableWidget->setSortingEnabled(__sortingEnabled);

        ClosePushButton->setText(QApplication::translate("Syn_BinCodesDlg", "Close", 0));
    } // retranslateUi

};

namespace Ui {
    class Syn_BinCodesDlg: public Ui_Syn_BinCodesDlg {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SYN_BINCODESDLG_H
